##Pandas

In [2]:
import pandas as pd

In [2]:
pd

In [3]:
pd.Series([64,82,79,55,86,45,86,98,45,74])

0    64
1    82
2    79
3    55
4    86
5    45
6    86
7    98
8    45
9    74
dtype: int64

In [4]:
marks=pd.Series([64,82,79,55,86,45,86,98,45,74], index=["Veer","Shreyas","Soham","Hemanshu","Tirth","Ozas","Akash","Vinit","Sammed","Abhishek"])
marks

Veer        64
Shreyas     82
Soham       79
Hemanshu    55
Tirth       86
Ozas        45
Akash       86
Vinit       98
Sammed      45
Abhishek    74
dtype: int64

In [5]:
marks["Shreyas"]

np.int64(82)

In [6]:
table={
    "name":["Shreyas","Veer","Soham"],
    "age":[20,20,22],
    "city":["Thane","Bhayandar","Titwala"]

}
type(table)

dict

In [7]:
table=pd.DataFrame(table)
table

      name  age       city
0  Shreyas   20      Thane
1     Veer   20  Bhayandar
2    Soham   22    Titwala

In [8]:
data=[["Shreyas", 82],[" Veer", 89],["Hemanshu", 85],["Soham", 75],]
table=pd.DataFrame(data, columns=["Name","Marks"])
print(table)

       Name  Marks
0   Shreyas     82
1      Veer     89
2  Hemanshu     85
3     Soham     75

In [9]:
import numpy as np
arr=np.array([[1,2],[5,6]])
df=pd.DataFrame(arr, columns=["A","B"])

In [10]:
##Read data from Excel File
df=pd.read_excel("data.xlsx")
df

       Name School  Marks
0   Shreyas   PDSS     75
1      Veer    FOS     86
2     Soham  JOAAS     56
3  Hemanshu    KPS     86

In [17]:
##Read data from CSV
df=pd.read_csv("data.csv")
df

       Name School  Marks
0   Shreyas   PDSS     75
1      Veer    FOS     86
2     Soham  JOAAS     56
3  Hemanshu    KPS     86

In [12]:
##Read data from JOSN
df=pd.read_json("data.json")
df

      name    lang
0  Shreyas  Python
1    Parth      JS

In [13]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [14]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [17]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [18]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [19]:
df.shape

(244, 7)

In [49]:
df=pd.read_csv("actors.csv")
df

,Name,Age,Date of Birth,Career Start Year,Debut Film,Best Movie,Worst Movie,Spouse,Upcoming Film(s)
0,Shah Rukh Khan,60,02-11-1965,1992,Deewana,Dilwale Dulhania Le Jayenge,Jab Harry Met Sejal,Gauri Khan,King
1,Aamir Khan,60,14-03-1965,1988,Qayamat Se Qayamat Tak,Lagaan,Sitaare Zameen Par,Kiran Rao (divorced),Happy Patel: Khatarnak Jasoos
2,Salman Khan,60,27-12-1965,1988,Biwi Ho To Aisi,Bajrangi Bhaijaan,Sikandar,Unmarried,Upcoming projects (post-Sikandar)
3,Akshay Kumar,58,09-09-1967,1991,Saugandh,Hera Pheri,Welcome to the Jungle,Twinkle Khanna,Upcoming projects
4,Hrithik Roshan,52,10-01-1974,2000,Kaho Naa... Pyaar Hai,Jodhaa Akbar,War 2,Saba Azad,Upcoming projects
5,Ranbir Kapoor,43,28-09-1982,2007,Saawariya,Rockstar,Animal,Alia Bhatt,Ramayana
6,Ajay Devgn,56,02-04-1969,1991,Phool Aur Kaante,Drishyam,Singham Again,Kajol,Upcoming projects
7,Amitabh Bachchan,83,11-10-1942,1969,Saat Hindustani,Sholay,Section 84,Jaya Bachchan,Upcoming projects
8,Vicky Kaushal,37,16-05-1988,2015,Masaan,Uri: The Surgical Strike,Chhaava,Katrina Kaif,Upcoming projects
9,Rajkummar Rao,41,31-08-1984,2010,Love Sex Aur Dhokha,Newton,Stree 2,Patralekhaa,Upcoming projects
10,Akshaye Khanna,50,28-03-1975,1997,Himalay Putra,Dil Chahta Hai,Section 84,Unmarried,Section 84
11,Ranveer Singh,40,06-07-1985,2010,Band Baaja Baaraat,Bajirao Mastani,Don 3,Deepika Padukone,Don 3
12,Deepika Padukone,40,05-01-1986,2006,Om Shanti Om,Padmaavat,Kalki 2898 AD,Ranveer Singh,Upcoming projects
13,Alia Bhatt,32,15-03-1993,2012,Student of the Year,Gangubai Kathiawadi,Jigra,Ranbir Kapoor,Upcoming projects
14,Kartik Aaryan,35,22-11-1990,2011,Pyaar Ka Punchnama,Bhool Bhulaiyaa 2,Bhool Bhulaiyaa 3,Unmarried,Upcoming projects
15,Shahid Kapoor,44,25-02-1981,2003,Ishq Vishk,Haider,Deva,Mira Rajput,Deva
16,Varun Dhawan,38,24-04-1987,2012,Student of the Year,Badlapur,Baby John,Natasha Dalal,Upcoming projects
17,Tiger Shroff,35,02-03-1990,2014,Heropanti,War,Baaghi 4,Unmarried,Baaghi 4
18,Ayushmann Khurrana,41,14-09-1984,2012,Vicky Donor,Andhadhun,Dream Girl 2,Tahira Kashyap,Upcoming projects
19,Sidharth Malhotra,40,16-01-1985,2012,Student of the Year,Shershaah,Yodha,Kiara Advani,Upcoming projects
20,Sunny Deol,69,19-10-1956,1983,Betaab,Gadar,Lahore 1947,Pooja Deol,Lahore 1947
21,Saif Ali Khan,55,16-08-1970,1993,Parampara,Omkara,Jewel Thief,Kareena Kapoor,Jewel Thief
22,Anil Kapoor,69,24-12-1956,1979,Hamare Tumhare,Mr. India,Subedaar,Sunita Kapoor,Subedaar
23,Bobby Deol,56,27-01-1969,1995,Barsaat,Animal,Kanguva,Tanya Deol,Kanguva
24,R Madhavan,55,01-06-1970,2000,Alaipayuthey,3 Idiots,Test,Sarita Birje,Test
25,Sanjay Dutt,66,29-07-1959,1981,Rocky,Munna Bhai M.B.B.S.,Welcome to the Jungle,Manyata Dutt,Welcome to the Jungle
26,Emraan Hashmi,46,24-03-1979,2003,Footpath,Awarapan,Tiger 3,Parveen Shahani,Upcoming projects

##Data Selection and Filteration

In [21]:
df['Name']

0         Shah Rukh Khan
1             Aamir Khan
2            Salman Khan
3           Akshay Kumar
4         Hrithik Roshan
5          Ranbir Kapoor
6             Ajay Devgn
7       Amitabh Bachchan
8          Vicky Kaushal
9          Rajkummar Rao
10        Akshaye Khanna
11         Ranveer Singh
12      Deepika Padukone
13            Alia Bhatt
14         Kartik Aaryan
15         Shahid Kapoor
16          Varun Dhawan
17          Tiger Shroff
18    Ayushmann Khurrana
19     Sidharth Malhotra
20            Sunny Deol
21         Saif Ali Khan
22           Anil Kapoor
23            Bobby Deol
24            R Madhavan
25           Sanjay Dutt
26         Emraan Hashmi
Name: Name, dtype: object

In [22]:
df[['Name','Upcoming Film(s)']]

                  Name                   Upcoming Film(s)
0       Shah Rukh Khan                               King
1           Aamir Khan      Happy Patel: Khatarnak Jasoos
2          Salman Khan  Upcoming projects (post-Sikandar)
3         Akshay Kumar                  Upcoming projects
4       Hrithik Roshan                  Upcoming projects
5        Ranbir Kapoor                           Ramayana
6           Ajay Devgn                  Upcoming projects
7     Amitabh Bachchan                  Upcoming projects
8        Vicky Kaushal                  Upcoming projects
9        Rajkummar Rao                  Upcoming projects
10      Akshaye Khanna                         Section 84
11       Ranveer Singh                              Don 3
12    Deepika Padukone                  Upcoming projects
13          Alia Bhatt                  Upcoming projects
14       Kartik Aaryan                  Upcoming projects
15       Shahid Kapoor                               Deva
16        Varun Dhawan                  Upcoming projects
17        Tiger Shroff                           Baaghi 4
18  Ayushmann Khurrana                  Upcoming projects
19   Sidharth Malhotra                  Upcoming projects
20          Sunny Deol                        Lahore 1947
21       Saif Ali Khan                        Jewel Thief
22         Anil Kapoor                           Subedaar
23          Bobby Deol                            Kanguva
24          R Madhavan                               Test
25         Sanjay Dutt              Welcome to the Jungle
26       Emraan Hashmi                  Upcoming projects

In [23]:
df.loc[0]

Name                              Shah Rukh Khan
Age                                           60
Date of Birth                         02-11-1965
Career Start Year                           1992
Debut Film                               Deewana
Best Movie           Dilwale Dulhania Le Jayenge
Worst Movie                  Jab Harry Met Sejal
Spouse                                Gauri Khan
Upcoming Film(s)                            King
Name: 0, dtype: object

In [24]:
df.iloc[:2,:2]

             Name  Age
0  Shah Rukh Khan   60
1      Aamir Khan   60

In [25]:
df.at[2,'Name']

'Salman Khan'

In [26]:
df[df['Age']>50]

,Name,Age,Date of Birth,Career Start Year,Debut Film,Best Movie,Worst Movie,Spouse,Upcoming Film(s)
0,Shah Rukh Khan,60,02-11-1965,1992,Deewana,Dilwale Dulhania Le Jayenge,Jab Harry Met Sejal,Gauri Khan,King
1,Aamir Khan,60,14-03-1965,1988,Qayamat Se Qayamat Tak,Lagaan,Sitaare Zameen Par,Kiran Rao (divorced),Happy Patel: Khatarnak Jasoos
2,Salman Khan,60,27-12-1965,1988,Biwi Ho To Aisi,Bajrangi Bhaijaan,Sikandar,Unmarried,Upcoming projects (post-Sikandar)
3,Akshay Kumar,58,09-09-1967,1991,Saugandh,Hera Pheri,Welcome to the Jungle,Twinkle Khanna,Upcoming projects
4,Hrithik Roshan,52,10-01-1974,2000,Kaho Naa... Pyaar Hai,Jodhaa Akbar,War 2,Saba Azad,Upcoming projects
6,Ajay Devgn,56,02-04-1969,1991,Phool Aur Kaante,Drishyam,Singham Again,Kajol,Upcoming projects
7,Amitabh Bachchan,83,11-10-1942,1969,Saat Hindustani,Sholay,Section 84,Jaya Bachchan,Upcoming projects
20,Sunny Deol,69,19-10-1956,1983,Betaab,Gadar,Lahore 1947,Pooja Deol,Lahore 1947
21,Saif Ali Khan,55,16-08-1970,1993,Parampara,Omkara,Jewel Thief,Kareena Kapoor,Jewel Thief
22,Anil Kapoor,69,24-12-1956,1979,Hamare Tumhare,Mr. India,Subedaar,Sunita Kapoor,Subedaar
23,Bobby Deol,56,27-01-1969,1995,Barsaat,Animal,Kanguva,Tanya Deol,Kanguva
24,R Madhavan,55,01-06-1970,2000,Alaipayuthey,3 Idiots,Test,Sarita Birje,Test
25,Sanjay Dutt,66,29-07-1959,1981,Rocky,Munna Bhai M.B.B.S.,Welcome to the Jungle,Manyata Dutt,Welcome to the Jungle

In [27]:
df.query("Age > 55")

,Name,Age,Date of Birth,Career Start Year,Debut Film,Best Movie,Worst Movie,Spouse,Upcoming Film(s)
0,Shah Rukh Khan,60,02-11-1965,1992,Deewana,Dilwale Dulhania Le Jayenge,Jab Harry Met Sejal,Gauri Khan,King
1,Aamir Khan,60,14-03-1965,1988,Qayamat Se Qayamat Tak,Lagaan,Sitaare Zameen Par,Kiran Rao (divorced),Happy Patel: Khatarnak Jasoos
2,Salman Khan,60,27-12-1965,1988,Biwi Ho To Aisi,Bajrangi Bhaijaan,Sikandar,Unmarried,Upcoming projects (post-Sikandar)
3,Akshay Kumar,58,09-09-1967,1991,Saugandh,Hera Pheri,Welcome to the Jungle,Twinkle Khanna,Upcoming projects
6,Ajay Devgn,56,02-04-1969,1991,Phool Aur Kaante,Drishyam,Singham Again,Kajol,Upcoming projects
7,Amitabh Bachchan,83,11-10-1942,1969,Saat Hindustani,Sholay,Section 84,Jaya Bachchan,Upcoming projects
20,Sunny Deol,69,19-10-1956,1983,Betaab,Gadar,Lahore 1947,Pooja Deol,Lahore 1947
22,Anil Kapoor,69,24-12-1956,1979,Hamare Tumhare,Mr. India,Subedaar,Sunita Kapoor,Subedaar
23,Bobby Deol,56,27-01-1969,1995,Barsaat,Animal,Kanguva,Tanya Deol,Kanguva
25,Sanjay Dutt,66,29-07-1959,1981,Rocky,Munna Bhai M.B.B.S.,Welcome to the Jungle,Manyata Dutt,Welcome to the Jungle

In [28]:
df=pd.read_csv("uncleaned_data.csv")

In [29]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [30]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [31]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [32]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [33]:
df.fillna(method="ffill")

C:\Users\Dinesh B Pawar\AppData\Local\Temp\ipykernel_23220\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [34]:
df.fillna(method="bfill")

C:\Users\Dinesh B Pawar\AppData\Local\Temp\ipykernel_23220\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [35]:
df.ffill()
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [36]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [37]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [38]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [39]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [40]:
df["City"].str.contains("delhi" ,case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [41]:
df2=df.dropna().copy()

In [42]:
df2["Age"]=df2["Age"].astype("int32")

In [43]:
df2.astype

<bound method NDFrame.astype of     Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021>

In [44]:
df2["Age Group"]=df2["Age"].apply(lambda x:"Adult" if x>=18 else "Minor") 
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [45]:
gender_map={"M":"Male", "F":"Female","O":"Other"}
df2["Gender"]=df2["Gender"].map(gender_map)
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    Male  david@example.com  12-11-2019     Adult
6  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult

In [46]:
df2["City"]=df2["City"].replace({"New York":"New York USA", "Los Angeles":"Los Angeles USA","Mumbai":"Mumbai India"})
df2

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25,New York USA,Female,alice@example.com,01-05-2021,Adult
2,Bob,30,Los Angeles USA,Male,bob@example.com,15-06-2020,Adult
4,David,22,Mumbai India,Male,david@example.com,12-11-2019,Adult
6,Alice,25,New York USA,Female,alice@example.com,01-05-2021,Adult
7,Alice,25,New York USA,Female,alice@example.com,01-05-2021,Adult

In [48]:
df.sort_values("Age")

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [50]:
df.sort_values("Age")

,Name,Age,Date of Birth,Career Start Year,Debut Film,Best Movie,Worst Movie,Spouse,Upcoming Film(s)
13,Alia Bhatt,32,15-03-1993,2012,Student of the Year,Gangubai Kathiawadi,Jigra,Ranbir Kapoor,Upcoming projects
14,Kartik Aaryan,35,22-11-1990,2011,Pyaar Ka Punchnama,Bhool Bhulaiyaa 2,Bhool Bhulaiyaa 3,Unmarried,Upcoming projects
17,Tiger Shroff,35,02-03-1990,2014,Heropanti,War,Baaghi 4,Unmarried,Baaghi 4
8,Vicky Kaushal,37,16-05-1988,2015,Masaan,Uri: The Surgical Strike,Chhaava,Katrina Kaif,Upcoming projects
16,Varun Dhawan,38,24-04-1987,2012,Student of the Year,Badlapur,Baby John,Natasha Dalal,Upcoming projects
19,Sidharth Malhotra,40,16-01-1985,2012,Student of the Year,Shershaah,Yodha,Kiara Advani,Upcoming projects
12,Deepika Padukone,40,05-01-1986,2006,Om Shanti Om,Padmaavat,Kalki 2898 AD,Ranveer Singh,Upcoming projects
11,Ranveer Singh,40,06-07-1985,2010,Band Baaja Baaraat,Bajirao Mastani,Don 3,Deepika Padukone,Don 3
18,Ayushmann Khurrana,41,14-09-1984,2012,Vicky Donor,Andhadhun,Dream Girl 2,Tahira Kashyap,Upcoming projects
9,Rajkummar Rao,41,31-08-1984,2010,Love Sex Aur Dhokha,Newton,Stree 2,Patralekhaa,Upcoming projects
5,Ranbir Kapoor,43,28-09-1982,2007,Saawariya,Rockstar,Animal,Alia Bhatt,Ramayana
15,Shahid Kapoor,44,25-02-1981,2003,Ishq Vishk,Haider,Deva,Mira Rajput,Deva
26,Emraan Hashmi,46,24-03-1979,2003,Footpath,Awarapan,Tiger 3,Parveen Shahani,Upcoming projects
10,Akshaye Khanna,50,28-03-1975,1997,Himalay Putra,Dil Chahta Hai,Section 84,Unmarried,Section 84
4,Hrithik Roshan,52,10-01-1974,2000,Kaho Naa... Pyaar Hai,Jodhaa Akbar,War 2,Saba Azad,Upcoming projects
21,Saif Ali Khan,55,16-08-1970,1993,Parampara,Omkara,Jewel Thief,Kareena Kapoor,Jewel Thief
24,R Madhavan,55,01-06-1970,2000,Alaipayuthey,3 Idiots,Test,Sarita Birje,Test
6,Ajay Devgn,56,02-04-1969,1991,Phool Aur Kaante,Drishyam,Singham Again,Kajol,Upcoming projects
23,Bobby Deol,56,27-01-1969,1995,Barsaat,Animal,Kanguva,Tanya Deol,Kanguva
3,Akshay Kumar,58,09-09-1967,1991,Saugandh,Hera Pheri,Welcome to the Jungle,Twinkle Khanna,Upcoming projects
0,Shah Rukh Khan,60,02-11-1965,1992,Deewana,Dilwale Dulhania Le Jayenge,Jab Harry Met Sejal,Gauri Khan,King
2,Salman Khan,60,27-12-1965,1988,Biwi Ho To Aisi,Bajrangi Bhaijaan,Sikandar,Unmarried,Upcoming projects (post-Sikandar)
1,Aamir Khan,60,14-03-1965,1988,Qayamat Se Qayamat Tak,Lagaan,Sitaare Zameen Par,Kiran Rao (divorced),Happy Patel: Khatarnak Jasoos
25,Sanjay Dutt,66,29-07-1959,1981,Rocky,Munna Bhai M.B.B.S.,Welcome to the Jungle,Manyata Dutt,Welcome to the Jungle
22,Anil Kapoor,69,24-12-1956,1979,Hamare Tumhare,Mr. India,Subedaar,Sunita Kapoor,Subedaar
20,Sunny Deol,69,19-10-1956,1983,Betaab,Gadar,Lahore 1947,Pooja Deol,Lahore 1947
7,Amitabh Bachchan,83,11-10-1942,1969,Saat Hindustani,Sholay,Section 84,Jaya Bachchan,Upcoming projects

In [63]:
df=df.sort_values("Age", ascending=False).copy()

In [61]:
df=df[['Name',"Age","Spouse"]].copy()

In [62]:
df

                  Name  Age                Spouse
0       Shah Rukh Khan   60            Gauri Khan
1           Aamir Khan   60  Kiran Rao (divorced)
2          Salman Khan   60             Unmarried
3         Akshay Kumar   58        Twinkle Khanna
4       Hrithik Roshan   52             Saba Azad
5        Ranbir Kapoor   43            Alia Bhatt
6           Ajay Devgn   56                 Kajol
7     Amitabh Bachchan   83         Jaya Bachchan
8        Vicky Kaushal   37          Katrina Kaif
9        Rajkummar Rao   41           Patralekhaa
10      Akshaye Khanna   50             Unmarried
11       Ranveer Singh   40      Deepika Padukone
12    Deepika Padukone   40         Ranveer Singh
13          Alia Bhatt   32         Ranbir Kapoor
14       Kartik Aaryan   35             Unmarried
15       Shahid Kapoor   44           Mira Rajput
16        Varun Dhawan   38         Natasha Dalal
17        Tiger Shroff   35             Unmarried
18  Ayushmann Khurrana   41        Tahira Kashyap
19   Sidharth Malhotra   40          Kiara Advani
20          Sunny Deol   69            Pooja Deol
21       Saif Ali Khan   55        Kareena Kapoor
22         Anil Kapoor   69         Sunita Kapoor
23          Bobby Deol   56            Tanya Deol
24          R Madhavan   55          Sarita Birje
25         Sanjay Dutt   66          Manyata Dutt
26       Emraan Hashmi   46       Parveen Shahani

In [64]:
df

                  Name  Age                Spouse
7     Amitabh Bachchan   83         Jaya Bachchan
20          Sunny Deol   69            Pooja Deol
22         Anil Kapoor   69         Sunita Kapoor
25         Sanjay Dutt   66          Manyata Dutt
2          Salman Khan   60             Unmarried
1           Aamir Khan   60  Kiran Rao (divorced)
0       Shah Rukh Khan   60            Gauri Khan
3         Akshay Kumar   58        Twinkle Khanna
23          Bobby Deol   56            Tanya Deol
6           Ajay Devgn   56                 Kajol
21       Saif Ali Khan   55        Kareena Kapoor
24          R Madhavan   55          Sarita Birje
4       Hrithik Roshan   52             Saba Azad
10      Akshaye Khanna   50             Unmarried
26       Emraan Hashmi   46       Parveen Shahani
15       Shahid Kapoor   44           Mira Rajput
5        Ranbir Kapoor   43            Alia Bhatt
18  Ayushmann Khurrana   41        Tahira Kashyap
9        Rajkummar Rao   41           Patralekhaa
12    Deepika Padukone   40         Ranveer Singh
11       Ranveer Singh   40      Deepika Padukone
19   Sidharth Malhotra   40          Kiara Advani
16        Varun Dhawan   38         Natasha Dalal
8        Vicky Kaushal   37          Katrina Kaif
14       Kartik Aaryan   35             Unmarried
17        Tiger Shroff   35             Unmarried
13          Alia Bhatt   32         Ranbir Kapoor

In [65]:

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}
 
df = pd.DataFrame(data)

In [66]:
df

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [72]:
df= df.melt(id_vars=["Name"], value_vars=["Math","Science","English"],var_name="Subject", value_name="Score").copy()

ValueError: value_name (Score) cannot match an element in the DataFrame columns.

In [76]:
df.pivot_table(index=None, columns="Subject", values="Score")

Subject  English  Math  Science
Score       89.0  85.0     87.0

In [77]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [78]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [79]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [85]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [86]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [90]:
df.groupby("Department").agg(["Salary"])

AttributeError: 'SeriesGroupBy' object has no attribute 'Salary'

In [3]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [5]:
employees
# departments

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [6]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [ ]:
pd.merge(employees,departments, on="DeptID") #Inner Join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [8]:
pd.merge(employees,departments, on="DeptID", how="left")  ## Left Join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [10]:
pd.merge(employees,departments, on="DeptID", how="right") ##Right Join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [11]:
 pd.merge(employees,departments, on="DeptID", how="outer") ##Outer Join - All

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [15]:
pd.concat([employees,departments],axis=0)

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10          NaN
1    2.0      Bob      20          NaN
2    3.0  Charlie      30          NaN
0    NaN      NaN      10           HR
1    NaN      NaN      20  Engineering
2    NaN      NaN      40    Marketing

In [16]:
pd.concat([employees,departments],axis=1)

   EmpID     Name  DeptID  DeptID     DeptName
0      1    Alice      10      10           HR
1      2      Bob      20      20  Engineering
2      3  Charlie      30      40    Marketing

In [ ]:
 df=df[df['Marks'] > 80.0]

In [25]:
df

       Name School  Marks
1      Veer    FOS     86
3  Hemanshu    KPS     86

In [29]:
df.to_csv("data_updated.csv" ,index=False)

In [30]:
with pd.ExcelWriter("report.xlsx") as writer:
    df.to_excel(writer, sheet_name="Shreyas", index=False)

In [32]:
data=[
    {"id":1,"name":"Shreyas", "address":{"city":"Mumbai","pincode":"400615"}},
    
    {"id":2,"name":"Parth", "address":{"city":"Pune","pincode":"400415"}}
]

In [33]:
df=pd.json_normalize(data)

In [34]:
df

   id     name address.city address.pincode
0   1  Shreyas       Mumbai          400615
1   2    Parth         Pune          400415